name: havadar
description: application of iranian league

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  localization: ^2.1.0
  marquee: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  url_launcher: ^6.1.7
  page_transition: ^2.0.9
  http: ^0.13.5
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  curved_navigation_bar: ^1.0.3
  shrink_sidemenu: ^2.0.0+2-null-safety
  flutter_share: ^2.0.0
  webview_flutter: ^3.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/avatars/
    - assets/feeds/
    - assets/icons/
    - assets/search/
    - assets/image/
    - assets/gif/
    - assets/product/
  fonts:
    - family: iranyekan
      fonts:
        - asset: assets/fonts/iranyekanB.ttf
          weight: 700
